// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: scanner/scanner.proto

package scanner

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ScannerClient is the client API for Scanner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScannerClient interface {
	Hexes(ctx context.Context, in *RangeMsg, opts ...grpc.CallOption) (*ArrHexMsg, error)
	Translatable(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ArrTranslatableMsg, error)
	Scanned(ctx context.Context, in *RangeMsg, opts ...grpc.CallOption) (*ArrScannedMsg, error)
	ChooseVariety(ctx context.Context, in *HexIntMsg, opts ...grpc.CallOption) (*empty.Empty, error)
	ChooseCaesura(ctx context.Context, in *HexIntMsg, opts ...grpc.CallOption) (*empty.Empty, error)
}

type scannerClient struct {
	cc grpc.ClientConnInterface
}

func NewScannerClient(cc grpc.ClientConnInterface) ScannerClient {
	return &scannerClient{cc}
}

func (c *scannerClient) Hexes(ctx context.Context, in *RangeMsg, opts ...grpc.CallOption) (*ArrHexMsg, error) {
	out := new(ArrHexMsg)
	err := c.cc.Invoke(ctx, "/scanner.Scanner/Hexes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scannerClient) Translatable(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ArrTranslatableMsg, error) {
	out := new(ArrTranslatableMsg)
	err := c.cc.Invoke(ctx, "/scanner.Scanner/Translatable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scannerClient) Scanned(ctx context.Context, in *RangeMsg, opts ...grpc.CallOption) (*ArrScannedMsg, error) {
	out := new(ArrScannedMsg)
	err := c.cc.Invoke(ctx, "/scanner.Scanner/Scanned", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scannerClient) ChooseVariety(ctx context.Context, in *HexIntMsg, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/scanner.Scanner/ChooseVariety", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scannerClient) ChooseCaesura(ctx context.Context, in *HexIntMsg, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/scanner.Scanner/ChooseCaesura", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScannerServer is the server API for Scanner service.
// All implementations must embed UnimplementedScannerServer
// for forward compatibility
type ScannerServer interface {
	Hexes(context.Context, *RangeMsg) (*ArrHexMsg, error)
	Translatable(context.Context, *empty.Empty) (*ArrTranslatableMsg, error)
	Scanned(context.Context, *RangeMsg) (*ArrScannedMsg, error)
	ChooseVariety(context.Context, *HexIntMsg) (*empty.Empty, error)
	ChooseCaesura(context.Context, *HexIntMsg) (*empty.Empty, error)
	mustEmbedUnimplementedScannerServer()
}

// UnimplementedScannerServer must be embedded to have forward compatible implementations.
type UnimplementedScannerServer struct {
}

func (UnimplementedScannerServer) Hexes(context.Context, *RangeMsg) (*ArrHexMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hexes not implemented")
}
func (UnimplementedScannerServer) Translatable(context.Context, *empty.Empty) (*ArrTranslatableMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Translatable not implemented")
}
func (UnimplementedScannerServer) Scanned(context.Context, *RangeMsg) (*ArrScannedMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Scanned not implemented")
}
func (UnimplementedScannerServer) ChooseVariety(context.Context, *HexIntMsg) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChooseVariety not implemented")
}
func (UnimplementedScannerServer) ChooseCaesura(context.Context, *HexIntMsg) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChooseCaesura not implemented")
}
func (UnimplementedScannerServer) mustEmbedUnimplementedScannerServer() {}

// UnsafeScannerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScannerServer will
// result in compilation errors.
type UnsafeScannerServer interface {
	mustEmbedUnimplementedScannerServer()
}

func RegisterScannerServer(s grpc.ServiceRegistrar, srv ScannerServer) {
	s.RegisterService(&Scanner_ServiceDesc, srv)
}

func _Scanner_Hexes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RangeMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScannerServer).Hexes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scanner.Scanner/Hexes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScannerServer).Hexes(ctx, req.(*RangeMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scanner_Translatable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScannerServer).Translatable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scanner.Scanner/Translatable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScannerServer).Translatable(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scanner_Scanned_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RangeMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScannerServer).Scanned(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scanner.Scanner/Scanned",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScannerServer).Scanned(ctx, req.(*RangeMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scanner_ChooseVariety_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HexIntMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScannerServer).ChooseVariety(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scanner.Scanner/ChooseVariety",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScannerServer).ChooseVariety(ctx, req.(*HexIntMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scanner_ChooseCaesura_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HexIntMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScannerServer).ChooseCaesura(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scanner.Scanner/ChooseCaesura",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScannerServer).ChooseCaesura(ctx, req.(*HexIntMsg))
	}
	return interceptor(ctx, in, info, handler)
}

// Scanner_ServiceDesc is the grpc.ServiceDesc for Scanner service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Scanner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scanner.Scanner",
	HandlerType: (*ScannerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hexes",
			Handler:    _Scanner_Hexes_Handler,
		},
		{
			MethodName: "Translatable",
			Handler:    _Scanner_Translatable_Handler,
		},
		{
			MethodName: "Scanned",
			Handler:    _Scanner_Scanned_Handler,
		},
		{
			MethodName: "ChooseVariety",
			Handler:    _Scanner_ChooseVariety_Handler,
		},
		{
			MethodName: "ChooseCaesura",
			Handler:    _Scanner_ChooseCaesura_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scanner/scanner.proto",
}
