// Code generated by protoc-gen-go. DO NOT EDIT.
// source: scanner/scanner.proto

package scanner

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RangeMsg struct {
	Start                int64    `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End                  int64    `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RangeMsg) Reset()         { *m = RangeMsg{} }
func (m *RangeMsg) String() string { return proto.CompactTextString(m) }
func (*RangeMsg) ProtoMessage()    {}
func (*RangeMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c85bb07bffd332d8, []int{0}
}

func (m *RangeMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RangeMsg.Unmarshal(m, b)
}
func (m *RangeMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RangeMsg.Marshal(b, m, deterministic)
}
func (m *RangeMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RangeMsg.Merge(m, src)
}
func (m *RangeMsg) XXX_Size() int {
	return xxx_messageInfo_RangeMsg.Size(m)
}
func (m *RangeMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_RangeMsg.DiscardUnknown(m)
}

var xxx_messageInfo_RangeMsg proto.InternalMessageInfo

func (m *RangeMsg) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *RangeMsg) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

type HexMsg struct {
	HexID                int64    `protobuf:"varint,1,opt,name=hexID,proto3" json:"hexID,omitempty"`
	Para                 bool     `protobuf:"varint,2,opt,name=para,proto3" json:"para,omitempty"`
	Txt                  string   `protobuf:"bytes,3,opt,name=txt,proto3" json:"txt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HexMsg) Reset()         { *m = HexMsg{} }
func (m *HexMsg) String() string { return proto.CompactTextString(m) }
func (*HexMsg) ProtoMessage()    {}
func (*HexMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c85bb07bffd332d8, []int{1}
}

func (m *HexMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HexMsg.Unmarshal(m, b)
}
func (m *HexMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HexMsg.Marshal(b, m, deterministic)
}
func (m *HexMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HexMsg.Merge(m, src)
}
func (m *HexMsg) XXX_Size() int {
	return xxx_messageInfo_HexMsg.Size(m)
}
func (m *HexMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_HexMsg.DiscardUnknown(m)
}

var xxx_messageInfo_HexMsg proto.InternalMessageInfo

func (m *HexMsg) GetHexID() int64 {
	if m != nil {
		return m.HexID
	}
	return 0
}

func (m *HexMsg) GetPara() bool {
	if m != nil {
		return m.Para
	}
	return false
}

func (m *HexMsg) GetTxt() string {
	if m != nil {
		return m.Txt
	}
	return ""
}

type ArrHexMsg struct {
	Hexes                []*HexMsg `protobuf:"bytes,1,rep,name=hexes,proto3" json:"hexes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ArrHexMsg) Reset()         { *m = ArrHexMsg{} }
func (m *ArrHexMsg) String() string { return proto.CompactTextString(m) }
func (*ArrHexMsg) ProtoMessage()    {}
func (*ArrHexMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c85bb07bffd332d8, []int{2}
}

func (m *ArrHexMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArrHexMsg.Unmarshal(m, b)
}
func (m *ArrHexMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArrHexMsg.Marshal(b, m, deterministic)
}
func (m *ArrHexMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArrHexMsg.Merge(m, src)
}
func (m *ArrHexMsg) XXX_Size() int {
	return xxx_messageInfo_ArrHexMsg.Size(m)
}
func (m *ArrHexMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ArrHexMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ArrHexMsg proto.InternalMessageInfo

func (m *ArrHexMsg) GetHexes() []*HexMsg {
	if m != nil {
		return m.Hexes
	}
	return nil
}

type HexWordMsg struct {
	HexID                int64    `protobuf:"varint,1,opt,name=hexID,proto3" json:"hexID,omitempty"`
	Order                int64    `protobuf:"varint,2,opt,name=order,proto3" json:"order,omitempty"`
	WordID               int64    `protobuf:"varint,3,opt,name=wordID,proto3" json:"wordID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HexWordMsg) Reset()         { *m = HexWordMsg{} }
func (m *HexWordMsg) String() string { return proto.CompactTextString(m) }
func (*HexWordMsg) ProtoMessage()    {}
func (*HexWordMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c85bb07bffd332d8, []int{3}
}

func (m *HexWordMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HexWordMsg.Unmarshal(m, b)
}
func (m *HexWordMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HexWordMsg.Marshal(b, m, deterministic)
}
func (m *HexWordMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HexWordMsg.Merge(m, src)
}
func (m *HexWordMsg) XXX_Size() int {
	return xxx_messageInfo_HexWordMsg.Size(m)
}
func (m *HexWordMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_HexWordMsg.DiscardUnknown(m)
}

var xxx_messageInfo_HexWordMsg proto.InternalMessageInfo

func (m *HexWordMsg) GetHexID() int64 {
	if m != nil {
		return m.HexID
	}
	return 0
}

func (m *HexWordMsg) GetOrder() int64 {
	if m != nil {
		return m.Order
	}
	return 0
}

func (m *HexWordMsg) GetWordID() int64 {
	if m != nil {
		return m.WordID
	}
	return 0
}

type WordMsg struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Txt                  string   `protobuf:"bytes,2,opt,name=txt,proto3" json:"txt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WordMsg) Reset()         { *m = WordMsg{} }
func (m *WordMsg) String() string { return proto.CompactTextString(m) }
func (*WordMsg) ProtoMessage()    {}
func (*WordMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c85bb07bffd332d8, []int{4}
}

func (m *WordMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WordMsg.Unmarshal(m, b)
}
func (m *WordMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WordMsg.Marshal(b, m, deterministic)
}
func (m *WordMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WordMsg.Merge(m, src)
}
func (m *WordMsg) XXX_Size() int {
	return xxx_messageInfo_WordMsg.Size(m)
}
func (m *WordMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_WordMsg.DiscardUnknown(m)
}

var xxx_messageInfo_WordMsg proto.InternalMessageInfo

func (m *WordMsg) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *WordMsg) GetTxt() string {
	if m != nil {
		return m.Txt
	}
	return ""
}

type ArrTranslatableMsg struct {
	Words                []*WordMsg    `protobuf:"bytes,1,rep,name=words,proto3" json:"words,omitempty"`
	Hexes                []*HexMsg     `protobuf:"bytes,2,rep,name=hexes,proto3" json:"hexes,omitempty"`
	HexWords             []*HexWordMsg `protobuf:"bytes,3,rep,name=hexWords,proto3" json:"hexWords,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ArrTranslatableMsg) Reset()         { *m = ArrTranslatableMsg{} }
func (m *ArrTranslatableMsg) String() string { return proto.CompactTextString(m) }
func (*ArrTranslatableMsg) ProtoMessage()    {}
func (*ArrTranslatableMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c85bb07bffd332d8, []int{5}
}

func (m *ArrTranslatableMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArrTranslatableMsg.Unmarshal(m, b)
}
func (m *ArrTranslatableMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArrTranslatableMsg.Marshal(b, m, deterministic)
}
func (m *ArrTranslatableMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArrTranslatableMsg.Merge(m, src)
}
func (m *ArrTranslatableMsg) XXX_Size() int {
	return xxx_messageInfo_ArrTranslatableMsg.Size(m)
}
func (m *ArrTranslatableMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ArrTranslatableMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ArrTranslatableMsg proto.InternalMessageInfo

func (m *ArrTranslatableMsg) GetWords() []*WordMsg {
	if m != nil {
		return m.Words
	}
	return nil
}

func (m *ArrTranslatableMsg) GetHexes() []*HexMsg {
	if m != nil {
		return m.Hexes
	}
	return nil
}

func (m *ArrTranslatableMsg) GetHexWords() []*HexWordMsg {
	if m != nil {
		return m.HexWords
	}
	return nil
}

type ScannedMsg struct {
	HexID                int64    `protobuf:"varint,1,opt,name=hexID,proto3" json:"hexID,omitempty"`
	Para                 bool     `protobuf:"varint,2,opt,name=para,proto3" json:"para,omitempty"`
	Txt                  string   `protobuf:"bytes,3,opt,name=txt,proto3" json:"txt,omitempty"`
	Scanned              string   `protobuf:"bytes,4,opt,name=scanned,proto3" json:"scanned,omitempty"`
	MusicalTemplate      string   `protobuf:"bytes,5,opt,name=musicalTemplate,proto3" json:"musicalTemplate,omitempty"`
	ScanningVariety      int64    `protobuf:"varint,6,opt,name=scanningVariety,proto3" json:"scanningVariety,omitempty"`
	Words                []string `protobuf:"bytes,7,rep,name=words,proto3" json:"words,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScannedMsg) Reset()         { *m = ScannedMsg{} }
func (m *ScannedMsg) String() string { return proto.CompactTextString(m) }
func (*ScannedMsg) ProtoMessage()    {}
func (*ScannedMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c85bb07bffd332d8, []int{6}
}

func (m *ScannedMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScannedMsg.Unmarshal(m, b)
}
func (m *ScannedMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScannedMsg.Marshal(b, m, deterministic)
}
func (m *ScannedMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScannedMsg.Merge(m, src)
}
func (m *ScannedMsg) XXX_Size() int {
	return xxx_messageInfo_ScannedMsg.Size(m)
}
func (m *ScannedMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ScannedMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ScannedMsg proto.InternalMessageInfo

func (m *ScannedMsg) GetHexID() int64 {
	if m != nil {
		return m.HexID
	}
	return 0
}

func (m *ScannedMsg) GetPara() bool {
	if m != nil {
		return m.Para
	}
	return false
}

func (m *ScannedMsg) GetTxt() string {
	if m != nil {
		return m.Txt
	}
	return ""
}

func (m *ScannedMsg) GetScanned() string {
	if m != nil {
		return m.Scanned
	}
	return ""
}

func (m *ScannedMsg) GetMusicalTemplate() string {
	if m != nil {
		return m.MusicalTemplate
	}
	return ""
}

func (m *ScannedMsg) GetScanningVariety() int64 {
	if m != nil {
		return m.ScanningVariety
	}
	return 0
}

func (m *ScannedMsg) GetWords() []string {
	if m != nil {
		return m.Words
	}
	return nil
}

type ArrScannedMsg struct {
	Hexes                []*ScannedMsg `protobuf:"bytes,1,rep,name=hexes,proto3" json:"hexes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ArrScannedMsg) Reset()         { *m = ArrScannedMsg{} }
func (m *ArrScannedMsg) String() string { return proto.CompactTextString(m) }
func (*ArrScannedMsg) ProtoMessage()    {}
func (*ArrScannedMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c85bb07bffd332d8, []int{7}
}

func (m *ArrScannedMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArrScannedMsg.Unmarshal(m, b)
}
func (m *ArrScannedMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArrScannedMsg.Marshal(b, m, deterministic)
}
func (m *ArrScannedMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArrScannedMsg.Merge(m, src)
}
func (m *ArrScannedMsg) XXX_Size() int {
	return xxx_messageInfo_ArrScannedMsg.Size(m)
}
func (m *ArrScannedMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ArrScannedMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ArrScannedMsg proto.InternalMessageInfo

func (m *ArrScannedMsg) GetHexes() []*ScannedMsg {
	if m != nil {
		return m.Hexes
	}
	return nil
}

func init() {
	proto.RegisterType((*RangeMsg)(nil), "scanner.RangeMsg")
	proto.RegisterType((*HexMsg)(nil), "scanner.HexMsg")
	proto.RegisterType((*ArrHexMsg)(nil), "scanner.ArrHexMsg")
	proto.RegisterType((*HexWordMsg)(nil), "scanner.HexWordMsg")
	proto.RegisterType((*WordMsg)(nil), "scanner.WordMsg")
	proto.RegisterType((*ArrTranslatableMsg)(nil), "scanner.ArrTranslatableMsg")
	proto.RegisterType((*ScannedMsg)(nil), "scanner.ScannedMsg")
	proto.RegisterType((*ArrScannedMsg)(nil), "scanner.ArrScannedMsg")
}

func init() { proto.RegisterFile("scanner/scanner.proto", fileDescriptor_c85bb07bffd332d8) }

var fileDescriptor_c85bb07bffd332d8 = []byte{
	// 459 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xcd, 0x8a, 0xd4, 0x40,
	0x10, 0x9e, 0x24, 0x9b, 0xf9, 0x29, 0x7f, 0x76, 0x6d, 0xd7, 0xa1, 0x99, 0xbd, 0x0c, 0x0d, 0x4a,
	0x44, 0xc8, 0xc8, 0x08, 0x1e, 0xbc, 0x0d, 0xcc, 0xc2, 0xec, 0x41, 0x90, 0xb8, 0xe8, 0xb9, 0x67,
	0xbb, 0xcd, 0x06, 0x32, 0x49, 0xa8, 0xf4, 0x62, 0xf6, 0x3d, 0x7c, 0x1a, 0x9f, 0xc1, 0x87, 0x92,
	0xf4, 0x4f, 0x12, 0x07, 0xf5, 0xb2, 0xa7, 0x74, 0x55, 0x7f, 0xdf, 0xd7, 0x5f, 0x55, 0xaa, 0xe0,
	0x45, 0x7d, 0xc3, 0x8b, 0x42, 0xe2, 0xca, 0x7e, 0xe3, 0x0a, 0x4b, 0x55, 0x92, 0x89, 0x0d, 0x17,
	0x17, 0x69, 0x59, 0xa6, 0xb9, 0x5c, 0xe9, 0xf4, 0xfe, 0xee, 0xdb, 0x4a, 0x1e, 0x2a, 0x75, 0x6f,
	0x50, 0x6c, 0x0d, 0xd3, 0x84, 0x17, 0xa9, 0xfc, 0x58, 0xa7, 0xe4, 0x1c, 0xc2, 0x5a, 0x71, 0x54,
	0xd4, 0x5b, 0x7a, 0x51, 0x90, 0x98, 0x80, 0x9c, 0x41, 0x20, 0x0b, 0x41, 0x7d, 0x9d, 0x6b, 0x8f,
	0x6c, 0x0b, 0xe3, 0x9d, 0x6c, 0x2c, 0xe3, 0x56, 0x36, 0x57, 0x5b, 0xc7, 0xd0, 0x01, 0x21, 0x70,
	0x52, 0x71, 0xe4, 0x9a, 0x32, 0x4d, 0xf4, 0xb9, 0x55, 0x51, 0x8d, 0xa2, 0xc1, 0xd2, 0x8b, 0x66,
	0x49, 0x7b, 0x64, 0x6b, 0x98, 0x6d, 0x10, 0xad, 0xd0, 0x4b, 0x2d, 0x24, 0x6b, 0xea, 0x2d, 0x83,
	0xe8, 0xd1, 0xfa, 0x34, 0x76, 0xb5, 0x98, 0xfb, 0xc4, 0xdc, 0xb2, 0x4f, 0x00, 0x3b, 0xd9, 0x7c,
	0x2d, 0x51, 0xfc, 0xfb, 0xf5, 0x73, 0x08, 0x4b, 0x14, 0x12, 0xad, 0x63, 0x13, 0x90, 0x39, 0x8c,
	0xbf, 0x97, 0x28, 0xae, 0xb6, 0xda, 0x42, 0x90, 0xd8, 0x88, 0xbd, 0x81, 0x89, 0x93, 0x7b, 0x0a,
	0x7e, 0x26, 0xac, 0x96, 0x9f, 0x09, 0x67, 0xd9, 0xef, 0x2d, 0xff, 0xf0, 0x80, 0x6c, 0x10, 0xaf,
	0x91, 0x17, 0x75, 0xce, 0x15, 0xdf, 0xe7, 0xba, 0x6f, 0xaf, 0x20, 0x6c, 0xd5, 0x9c, 0xf9, 0xb3,
	0xce, 0xbc, 0x55, 0x4e, 0xcc, 0x75, 0x5f, 0xa4, 0xff, 0xbf, 0x22, 0xc9, 0x0a, 0xa6, 0xb7, 0xa6,
	0xc8, 0x9a, 0x06, 0x1a, 0xf9, 0x7c, 0x88, 0x74, 0xa2, 0x1d, 0x88, 0xfd, 0xf2, 0x00, 0x3e, 0x6b,
	0x80, 0x78, 0xe0, 0x4f, 0x21, 0x14, 0xec, 0xd8, 0x08, 0x7a, 0xa2, 0xb3, 0x2e, 0x24, 0x11, 0x9c,
	0x1e, 0xee, 0xea, 0xec, 0x86, 0xe7, 0xd7, 0xf2, 0x50, 0xe5, 0x5c, 0x49, 0x1a, 0x6a, 0xc4, 0x71,
	0xba, 0x45, 0x6a, 0x52, 0x56, 0xa4, 0x5f, 0x38, 0x66, 0x52, 0xdd, 0xd3, 0xb1, 0x76, 0x72, 0x9c,
	0x6e, 0x9d, 0x9a, 0xc6, 0x4d, 0x96, 0x41, 0x34, 0xb3, 0x6d, 0x62, 0x1f, 0xe0, 0xc9, 0x06, 0x71,
	0x50, 0xd0, 0xeb, 0x3f, 0x87, 0xa3, 0xef, 0x46, 0x8f, 0xb1, 0xbd, 0x5b, 0xff, 0xf4, 0x60, 0x62,
	0xb2, 0x48, 0xde, 0x42, 0xb8, 0xd3, 0x0d, 0x7d, 0xd6, 0x11, 0xdc, 0xa8, 0x2f, 0x48, 0x97, 0xea,
	0x66, 0x90, 0x8d, 0xc8, 0x25, 0x3c, 0x1e, 0xfe, 0x5b, 0x32, 0x8f, 0xcd, 0xea, 0xc4, 0x6e, 0x75,
	0xe2, 0xcb, 0x76, 0x75, 0x16, 0x17, 0x43, 0xf6, 0xd1, 0x34, 0xb0, 0x11, 0x79, 0xef, 0x3c, 0x88,
	0xbf, 0x3d, 0x3d, 0x1f, 0x92, 0xfb, 0x0a, 0xd8, 0x68, 0x3f, 0xd6, 0xcf, 0xbc, 0xfb, 0x1d, 0x00,
	0x00, 0xff, 0xff, 0x1b, 0xc5, 0xfc, 0x87, 0xd1, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ScannerClient is the client API for Scanner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ScannerClient interface {
	Hexes(ctx context.Context, in *RangeMsg, opts ...grpc.CallOption) (*ArrHexMsg, error)
	Translatable(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ArrTranslatableMsg, error)
	Scanned(ctx context.Context, in *RangeMsg, opts ...grpc.CallOption) (*ArrScannedMsg, error)
}

type scannerClient struct {
	cc *grpc.ClientConn
}

func NewScannerClient(cc *grpc.ClientConn) ScannerClient {
	return &scannerClient{cc}
}

func (c *scannerClient) Hexes(ctx context.Context, in *RangeMsg, opts ...grpc.CallOption) (*ArrHexMsg, error) {
	out := new(ArrHexMsg)
	err := c.cc.Invoke(ctx, "/scanner.Scanner/Hexes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scannerClient) Translatable(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ArrTranslatableMsg, error) {
	out := new(ArrTranslatableMsg)
	err := c.cc.Invoke(ctx, "/scanner.Scanner/Translatable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scannerClient) Scanned(ctx context.Context, in *RangeMsg, opts ...grpc.CallOption) (*ArrScannedMsg, error) {
	out := new(ArrScannedMsg)
	err := c.cc.Invoke(ctx, "/scanner.Scanner/Scanned", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScannerServer is the server API for Scanner service.
type ScannerServer interface {
	Hexes(context.Context, *RangeMsg) (*ArrHexMsg, error)
	Translatable(context.Context, *empty.Empty) (*ArrTranslatableMsg, error)
	Scanned(context.Context, *RangeMsg) (*ArrScannedMsg, error)
}

// UnimplementedScannerServer can be embedded to have forward compatible implementations.
type UnimplementedScannerServer struct {
}

func (*UnimplementedScannerServer) Hexes(ctx context.Context, req *RangeMsg) (*ArrHexMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hexes not implemented")
}
func (*UnimplementedScannerServer) Translatable(ctx context.Context, req *empty.Empty) (*ArrTranslatableMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Translatable not implemented")
}
func (*UnimplementedScannerServer) Scanned(ctx context.Context, req *RangeMsg) (*ArrScannedMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Scanned not implemented")
}

func RegisterScannerServer(s *grpc.Server, srv ScannerServer) {
	s.RegisterService(&_Scanner_serviceDesc, srv)
}

func _Scanner_Hexes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RangeMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScannerServer).Hexes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scanner.Scanner/Hexes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScannerServer).Hexes(ctx, req.(*RangeMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scanner_Translatable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScannerServer).Translatable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scanner.Scanner/Translatable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScannerServer).Translatable(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scanner_Scanned_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RangeMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScannerServer).Scanned(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scanner.Scanner/Scanned",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScannerServer).Scanned(ctx, req.(*RangeMsg))
	}
	return interceptor(ctx, in, info, handler)
}

var _Scanner_serviceDesc = grpc.ServiceDesc{
	ServiceName: "scanner.Scanner",
	HandlerType: (*ScannerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hexes",
			Handler:    _Scanner_Hexes_Handler,
		},
		{
			MethodName: "Translatable",
			Handler:    _Scanner_Translatable_Handler,
		},
		{
			MethodName: "Scanned",
			Handler:    _Scanner_Scanned_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scanner/scanner.proto",
}
